apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wow-bg-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv-wow-bg-data