apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wow-bg-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-wow-bg-data